/* generated by tools/build-dist.mjs — DO NOT EDIT. 編集は src/ のアトミック分割ソースへ */
/* ============================================================
   liquid-glass.js — lens engine / Spring / virtual light / init
   plain script, zero dependencies. requires css/tokens.css +
   css/liquid-glass.css. 値の由来は tokens.json の $description。
   ============================================================ */
(function () {
  'use strict';

  var root = document.documentElement;
  var reduceMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
  var reduceTransp = matchMedia('(prefers-reduced-transparency: reduce)').matches;

  /* ---------- capability detection ----------
     backdrop-filter: url() は Chromium 限定。@supports は Safari で
     偽陽性があるため UA 判定を併用する（リサーチ確定事項）。 */
  var isChromium = /Chrom(e|ium)\//.test(navigator.userAgent);
  var bfOK = CSS.supports('backdrop-filter', 'blur(1px)') ||
             CSS.supports('-webkit-backdrop-filter', 'blur(1px)');
  var urlOK = CSS.supports('backdrop-filter', 'url(#f)');
  var mode = reduceTransp ? 'opaque'
           : (isChromium && bfOK && urlOK) ? 'lens'
           : bfOK ? 'baseline' : 'opaque';

  root.classList.add('lg-js', 'lg-mode-' + mode);

  /* 共有ポインタ座標 — スクロール時の hover 実判定用。Chrome は次の mousemove まで
     :hover を再計算しないことがあるため、:hover 擬似クラスは信用しない */
  var lgPX = -1, lgPY = -1;
  document.addEventListener('pointermove', function (e) { lgPX = e.clientX; lgPY = e.clientY; }, true);
  function lgPointerOver(el) { /* 実ヒットテスト（現在のポインタ座標が el 上か） */
    if (lgPX < 0) return false;
    var r = el.getBoundingClientRect();
    if (lgPX < r.left || lgPX > r.right || lgPY < r.top || lgPY > r.bottom) return false;
    var at = document.elementFromPoint(lgPX, lgPY);
    return !!(at && (at === el || el.contains(at)));
  }

  /* ---------- token access (single source = CSS custom properties) ---------- */
  var rootCS = null;
  function cssVal(name) {
    if (!rootCS) rootCS = getComputedStyle(root);
    return rootCS.getPropertyValue(name).trim();
  }
  function cssNum(name, fallback) {
    var n = parseFloat(cssVal(name));
    return isNaN(n) ? fallback : n;
  }

  var tok = null;
  var variants = null;
  function ensureTokens() {
    if (!tok) readTokens();
  }
  function readTokens() {
    rootCS = null;
    tok = {
      k: cssNum('--lg-motion-gel-k', 440),
      zeta: cssNum('--lg-motion-gel-zeta', 0.65),
      pressScale: cssNum('--lg-motion-gel-press-scale', 0.97),
      pressMs: cssNum('--lg-motion-gel-press-duration', 90),
      caR: cssNum('--lg-ref-lens-ca-split-r', 0.86),
      caB: cssNum('--lg-ref-lens-ca-split-b', 1.22),
      mapMax: cssNum('--lg-ref-lens-map-max', 384),
      modalEnter: cssNum('--lg-modal-enter-scale', 0.94),
      fadeMs: cssNum('--lg-ref-duration-fade', 350)
    };
    /* variant lookup table — buildFilter 内分岐ではなく tokens 由来の表 */
    variants = {};
    ['regular', 'clear'].forEach(function (v) {
      var p = '--lg-material-' + v + '-';
      variants[v] = {
        falloffRatio: cssNum(p + 'falloff-ratio', 0.45),
        scaleRatio: cssNum(p + 'scale-ratio', 0.32),
        scaleMax: cssNum(p + 'scale-max', 44),
        scaleMin: cssNum(p + 'scale-min', 12),
        ca: cssNum(p + 'ca', 4),
        saturate: cssNum(p + 'saturate', 1.4),
        chainBlur: cssNum(p + 'chain-blur', 0)
      };
    });
  }

  /* ---------- 観測者効果 observer effect（R16） ----------
     トークンは範囲を定義し、観測者シードが値を確定する。
     mode: html[data-lg-observer] = "personal"（ブラウザごとに永続シード）
           / "fixed"（既定。data-lg-seed か 0 で決定的）
     揺れる軸: 分光色相・光源基準角・呼吸周期・個体差プール。
     不変: コントラスト・予算・レイアウト・状態色の意味。
     accent（primary）は環境光と同角で回る = 背景のうっすらした色と常に同調。 */
  var obsSeedOffset = 0;
  var observerInfo = { mode: 'fixed', seed: '0' };

  function obsHash(str) { /* xorshift 系の決定的ハッシュ → [0,1) を4本 */
    var h = 2166136261;
    for (var i = 0; i < str.length; i++) {
      h ^= str.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    var out = [];
    for (var j = 0; j < 4; j++) {
      h ^= h << 13; h ^= h >>> 17; h ^= h << 5;
      out.push(((h >>> 0) % 10000) / 10000);
    }
    return out;
  }
  function hexToHsl(hex) {
    var n = parseInt(hex.slice(1), 16);
    var r = ((n >> 16) & 255) / 255, g = ((n >> 8) & 255) / 255, b = (n & 255) / 255;
    var mx = Math.max(r, g, b), mn = Math.min(r, g, b), l = (mx + mn) / 2;
    var d = mx - mn, h = 0, s = 0;
    if (d) {
      s = l > 0.5 ? d / (2 - mx - mn) : d / (mx + mn);
      h = mx === r ? (g - b) / d + (g < b ? 6 : 0) : mx === g ? (b - r) / d + 2 : (r - g) / d + 4;
      h *= 60;
    }
    return [h, s, l];
  }
  function hslCss(h, s, l) {
    return 'hsl(' + ((h % 360 + 360) % 360).toFixed(1) + ', ' +
      (s * 100).toFixed(1) + '%, ' + (l * 100).toFixed(1) + '%)';
  }
  function initObserver() {
    var mode = root.getAttribute('data-lg-observer') === 'personal' ? 'personal' : 'fixed';
    var seed;
    if (mode === 'personal') {
      try {
        seed = localStorage.getItem('lg-observer-seed');
        if (!seed) {
          seed = String(Math.floor(Math.random() * 1e9));
          localStorage.setItem('lg-observer-seed', seed);
        }
      } catch (_) { seed = '0'; }
    } else {
      seed = root.getAttribute('data-lg-seed') || '0';
    }
    var r = obsHash('lg:' + seed);
    observerInfo = { mode: mode, seed: seed };

    /* 軸1: 分光の色相回転（cool/warm を同角回転 = 補色関係を保つ） */
    var rot = cssNum('--lg-observer-spectrum-rotation', 0);
    if (rot > 0) {
      var deg = (r[0] * 2 - 1) * rot;
      ['cool', 'warm'].forEach(function (k) {
        var hex = cssVal('--lg-ref-color-spectrum-' + k);
        if (/^#[0-9a-f]{6}$/i.test(hex)) {
          var hsl = hexToHsl(hex);
          root.style.setProperty('--lg-light-rim-spec-' + k, hslCss(hsl[0] + deg, hsl[1], hsl[2]));
        }
      });
      observerInfo.spectrumShift = Math.round(deg);
    }
    /* 軸2: 光源の基準角 */
    var ar = cssNum('--lg-observer-angle-range', 0);
    if (ar > 0) {
      var base = 215 + (r[1] * 2 - 1) * ar;
      root.style.setProperty('--lg-la', base.toFixed(1) + 'deg');
      observerInfo.angle = Math.round(base);
    }
    /* 軸3: 呼吸周期 */
    var bmin = cssNum('--lg-observer-breath-min', 0);
    var bmax = cssNum('--lg-observer-breath-max', 0);
    if (bmax > bmin && bmin > 0) {
      var period = bmin + r[2] * (bmax - bmin);
      root.style.setProperty('--lg-light-breath-period', Math.round(period) + 'ms');
      observerInfo.breath = Math.round(period);
    }
    /* 軸4: 環境光の色相（hover 不要・SP でも開いた瞬間に見える）。
       primary（accent）も同角で回し、背景のうっすらした色と常に同調させる
       （R16 改訂: 状態色 danger/warning/success の意味色は不変のまま） */
    var amb = cssNum('--lg-observer-ambient-rotation', 0);
    if (amb > 0) {
      var ambDeg = r[3] * amb; /* フルホイール配置（R16補遺2） */
      root.style.setProperty('--lg-obs-ambient', ambDeg.toFixed(1) + 'deg');
      observerInfo.ambient = Math.round(ambDeg);
      ['accent', 'accent-deep', 'accent-solid'].forEach(function (k) {
        var hex = cssVal('--lg-ref-color-' + k);
        if (/^#[0-9a-f]{6}$/i.test(hex)) {
          var hsl = hexToHsl(hex);
          root.style.setProperty('--lg-ref-color-' + k, hslCss(hsl[0] + ambDeg, hsl[1], hsl[2]));
        }
      });
    }
    /* 軸5: 個体差プールのずれ */
    obsSeedOffset = Math.floor(((r[0] + r[3]) * 7) % 4);
  }

  /* ---------- 体質 physique（R17） ----------
     動き・光学の2軸 trait（0〜1）が、対応する性質群を min/max の間で確定する。
     trait のソース（優先順）:
       1. ホスト指定: html[data-lg-trait-motion / -optics]（抽象値のみ。
          生の個人データ・検索履歴等は DS の境界の外 — 受けない）
       2. 端末内学習: 操作テンポ（personal モードのみ。翌訪問に反映）
       3. 既定トークン（0.5 = 現行値）
     OS 信号: prefers-reduced-motion は motion trait を 0 に固定。 */
  var physiqueInfo = { motion: 0.5, optics: 0.5, source: 'default' };

  function phLerp(minName, maxName, t) {
    var a = cssNum(minName, 0), b = cssNum(maxName, 0);
    return a + (b - a) * t;
  }
  function initPhysique() {
    var mode = root.getAttribute('data-lg-observer') === 'personal' ? 'personal' : 'fixed';
    var m = parseFloat(root.getAttribute('data-lg-trait-motion'));
    var o = parseFloat(root.getAttribute('data-lg-trait-optics'));
    var source = 'default';
    if (!isNaN(m) || !isNaN(o)) source = 'host';
    if (isNaN(m) && mode === 'personal') {
      try { m = parseFloat(localStorage.getItem('lg-trait-motion')); source = 'learned'; } catch (_) {}
    }
    if (isNaN(m)) m = cssNum('--lg-physique-motion-default', 0.5);
    if (isNaN(o)) o = cssNum('--lg-physique-optics-default', 0.5);
    /* 深夜は光学が静かに（端末時計のみ・保存しない） */
    var h = new Date().getHours();
    if (source !== 'host' && (h >= 23 || h < 6)) o = Math.max(0, o - 0.15);
    if (reduceMotion) m = 0;
    m = Math.min(1, Math.max(0, m));
    o = Math.min(1, Math.max(0, o));
    physiqueInfo = { motion: m, optics: o, source: source };

    var set = function (name, v) { root.style.setProperty(name, String(v)); };
    /* 動き軸 */
    set('--lg-motion-gel-wobble-zeta', phLerp('--lg-physique-wobble-zeta-min', '--lg-physique-wobble-zeta-max', m).toFixed(3));
    set('--lg-motion-gel-squash-y', phLerp('--lg-physique-squash-y-min', '--lg-physique-squash-y-max', m).toFixed(3));
    set('--lg-motion-gel-stretch-x', phLerp('--lg-physique-stretch-x-min', '--lg-physique-stretch-x-max', m).toFixed(3));
    set('--lg-motion-gel-hover-scale', phLerp('--lg-physique-hover-scale-min', '--lg-physique-hover-scale-max', m).toFixed(3));
    set('--lg-light-breath-depth', phLerp('--lg-physique-breath-depth-min', '--lg-physique-breath-depth-max', m).toFixed(3));
    /* 光学軸 */
    set('--lg-motion-gel-optics-press', phLerp('--lg-physique-optics-press-min', '--lg-physique-optics-press-max', o).toFixed(3));
    set('--lg-ref-lens-ca', phLerp('--lg-physique-ca-min', '--lg-physique-ca-max', o).toFixed(2));
    set('--lg-ref-lens-organic', phLerp('--lg-physique-organic-min', '--lg-physique-organic-max', o).toFixed(3));
    set('--lg-light-hover-intensity', phLerp('--lg-physique-hover-int-min', '--lg-physique-hover-int-max', o).toFixed(3));

    /* 端末内学習（personal のみ）: 操作テンポ → 動き trait を翌訪問へ ±0.08 まで漂わせる */
    if (mode === 'personal' && !reduceMotion) {
      var taps = [];
      document.addEventListener('pointerdown', function () {
        var t = performance.now();
        taps.push(t);
        if (taps.length > 12) taps.shift();
      });
      window.addEventListener('pagehide', function () {
        if (taps.length < 5) return;
        var gaps = [];
        for (var i = 1; i < taps.length; i++) gaps.push(taps[i] - taps[i - 1]);
        gaps.sort(function (a, b) { return a - b; });
        var median = gaps[Math.floor(gaps.length / 2)];
        /* 速いテンポ（<1.2s）→ 活発へ、遅い（>4s）→ 静かへ */
        var drift = median < 1200 ? 0.04 : median > 4000 ? -0.04 : 0;
        if (!drift) return;
        var next = Math.min(0.58, Math.max(0.42, m + drift)); /* 学習の可動域は ±0.08 */
        try { localStorage.setItem('lg-trait-motion', next.toFixed(3)); } catch (_) {}
      });
    }
  }

  /* ---------- 環境信号 signals（R18） ----------
     素材が置かれた「現実の環境」に応答する4信号。すべて端末内で完結し、
     ネットワーク送信・生データの保存はしない（R17 のプライバシー境界の内側）。
       太陽同期    : 端末時刻から太陽方位を近似し、仮想光源の基準角を実際の太陽に合わせる
       傾き応答    : 端末の傾きに光源が 1:1 追従（SP の hover 代替。iOS は明示許諾）
       バッテリー  : 残量低下で呼吸が浅く・省エネに（生き物の疲労 + 描画コスト配慮）
       懐き        : 訪問日数で生命徴が開く（初訪は人見知り。personal モードのみ）
     各信号は --lg-signals-* トークンで個別に無効化できる（apple-quiet は全オフ） */
  var signalsInfo = { sun: 'off', tilt: 'off', battery: 'off', affinity: 'off' };
  var sigBase = null;   /* physique 適用後の基準値（乗算のベース） */
  var sigTired = false; /* バッテリー疲労状態 */
  var sigAffinity = 1;  /* 懐き 0〜1（fixed モードは常に 1 = 決定性維持） */

  /* 太陽方位の近似: 正午 = 既定角 215、日の出/日の入りで ±70°。夜は既定角。
     観測者の角度個性（R16 軸2）はオフセットとして太陽の上に残る */
  function sunAngle() {
    var d = new Date();
    var t = d.getHours() + d.getMinutes() / 60;
    if (t < 6 || t > 18) return null; /* 夜 */
    return 215 + ((t - 12) / 6) * 70;
  }

  /* 信号による補正を physique の基準値に乗せて再適用する。
     battery は非同期解決のため、後から呼び直しても安全な冪等設計 */
  function applySignalMods() {
    if (!sigBase) return;
    var a = sigAffinity;
    var fBreath = (0.4 + 0.6 * a) * (sigTired ? 0.5 : 1);
    var fHover = (0.6 + 0.4 * a) * (sigTired ? 0.85 : 1);
    root.style.setProperty('--lg-light-breath-depth', (sigBase.breath * fBreath).toFixed(3));
    root.style.setProperty('--lg-light-hover-intensity', (sigBase.hover * fHover).toFixed(3));
    /* 疲れているときは押しても屈折が深く潰れない（省エネの身体性） */
    var op = sigTired ? sigBase.opress + (1 - sigBase.opress) * 0.5 : sigBase.opress;
    root.style.setProperty('--lg-motion-gel-optics-press', op.toFixed(3));
  }

  var tiltAttach = null; /* iOS: 許諾後に呼ぶ実体（enableTilt から） */
  function initSignals() {
    sigBase = {
      breath: cssNum('--lg-light-breath-depth', 0.3),
      hover: cssNum('--lg-light-hover-intensity', 0.8),
      opress: cssNum('--lg-motion-gel-optics-press', 0.3)
    };
    var personal = root.getAttribute('data-lg-observer') === 'personal';
    var obsOffset = (observerInfo.angle != null) ? observerInfo.angle - 215 : 0;
    var baseAngle = 215 + obsOffset;

    /* --- 太陽同期 --- */
    if (cssNum('--lg-signals-sun-sync', 0) > 0) {
      var sa = sunAngle();
      if (sa != null) {
        baseAngle = sa + obsOffset;
        root.style.setProperty('--lg-la', baseAngle.toFixed(1) + 'deg');
        signalsInfo.sun = { angle: Math.round(baseAngle) };
      } else {
        signalsInfo.sun = 'night';
      }
    }

    /* --- 傾き応答（光源が端末の傾きに 1:1 追従。公理5: 追従に慣性なし） --- */
    if (cssNum('--lg-signals-tilt', 0) > 0 && typeof DeviceOrientationEvent !== 'undefined') {
      var neutralBeta = null, pendTilt = null;
      var onTilt = function (e) {
        if (e.gamma == null || e.beta == null) return;
        if (neutralBeta == null) neutralBeta = e.beta; /* 最初の姿勢を中立に */
        var g = Math.max(-45, Math.min(45, e.gamma));
        var db = Math.max(-45, Math.min(45, e.beta - neutralBeta));
        var off = g * 1.2 + db * 0.6;
        if (pendTilt != null) return; /* rAF 間引き */
        pendTilt = requestAnimationFrame(function () {
          pendTilt = null;
          root.style.setProperty('--lg-la', (baseAngle + off).toFixed(1) + 'deg');
        });
        signalsInfo.tilt = 'active';
      };
      tiltAttach = function () {
        window.addEventListener('deviceorientation', onTilt);
        signalsInfo.tilt = 'listening';
      };
      if (typeof DeviceOrientationEvent.requestPermission === 'function') {
        signalsInfo.tilt = 'needs-permission'; /* iOS: LiquidGlass.enableTilt() をジェスチャーから */
      } else {
        tiltAttach();
      }
    }

    /* --- 懐き（訪問日数 → 生命徴の開き。personal のみ・日単位・リセット可） --- */
    if (cssNum('--lg-signals-affinity', 0) > 0 && personal) {
      var days = 1;
      try {
        var rec = JSON.parse(localStorage.getItem('lg-affinity') || '{}');
        var today = new Date().toISOString().slice(0, 10);
        days = (rec.n || 0) + (rec.d === today ? 0 : 1);
        if (rec.d !== today) localStorage.setItem('lg-affinity', JSON.stringify({ d: today, n: days }));
        else days = rec.n;
      } catch (_) {}
      var max = cssNum('--lg-signals-affinity-days-max', 8);
      sigAffinity = Math.min(1, days / max);
      signalsInfo.affinity = { days: days, openness: +sigAffinity.toFixed(2) };
      /* 個体差の風合いも通うほど開く（applyLens より前に確定させる） */
      var org = cssNum('--lg-ref-lens-organic', 0.12);
      root.style.setProperty('--lg-ref-lens-organic', (org * (0.5 + 0.5 * sigAffinity)).toFixed(3));
    }

    /* --- バッテリー = 元気（Battery API がある環境のみ） --- */
    if (cssNum('--lg-signals-battery', 0) > 0 && navigator.getBattery) {
      navigator.getBattery().then(function (b) {
        var update = function () {
          sigTired = b.level <= 0.2 && !b.charging;
          signalsInfo.battery = { level: +b.level.toFixed(2), tired: sigTired };
          applySignalMods();
        };
        b.addEventListener('levelchange', update);
        b.addEventListener('chargingchange', update);
        update();
      }).catch(function () {});
    }

    applySignalMods();
  }

  /* ============================================================
     displacement map — rounded-rect SDF 数値勾配 × convex squircle
     ⁴√(1-(1-x)⁴)。R/G = X/Y 変位、128 中立。エッジのみ屈折。
     geometry キャッシュ: w×h×r×falloff キーで再利用（LP 規模対応）。
     ============================================================ */
  function roundedSDF(px, py, hw, hh, r) {
    var qx = Math.abs(px) - (hw - r);
    var qy = Math.abs(py) - (hh - r);
    var ax = Math.max(qx, 0), ay = Math.max(qy, 0);
    return Math.min(Math.max(qx, qy), 0) + Math.hypot(ax, ay) - r; /* <0 inside */
  }

  var seedCounter = 0; /* 個体プール（4体）: 同一 geometry でも指紋が異なる */
  var mapCache = new Map();    /* key -> data URI */
  var filterCache = new Map(); /* key -> filter id */
  var defs = null, idc = 0;

  function makeMapURI(w, h, r, falloff, seed) {
    var ds = Math.min(1, tok.mapMax / Math.max(w, h)); /* downscale cap */
    var mw = Math.max(2, Math.round(w * ds));
    var mh = Math.max(2, Math.round(h * ds));
    var mr = r * ds;
    var mf = Math.max(2, falloff * ds);
    var key = mw + 'x' + mh + 'r' + Math.round(mr * 2) + 'f' + Math.round(mf * 2) + 's' + seed;
    var hit = mapCache.get(key);
    if (hit) return hit;

    var c = document.createElement('canvas');
    c.width = mw; c.height = mh;
    var ctx = c.getContext('2d');
    var img = ctx.createImageData(mw, mh);
    var d = img.data;
    var hw = mw / 2, hh = mh / 2, e = 0.75;
    var organic = cssNum('--lg-ref-lens-organic', 0);
    for (var y = 0; y < mh; y++) {
      for (var x = 0; x < mw; x++) {
        var px = x + 0.5 - hw, py = y + 0.5 - hh;
        var s = roundedSDF(px, py, hw, hh, mr);
        var dx = 0, dy = 0;
        if (s < 0) {
          var t = Math.min(-s / mf, 1);
          var height = Math.pow(1 - Math.pow(1 - t, 4), 0.25); /* convex squircle */
          var mag = 1 - height;                                 /* edge-only */
          /* 個体差（生命徴・R13）: 低周波の有機ノイズで屈折に一枚ごとの指紋を与える */
          if (organic > 0) {
            mag *= 1 + organic * Math.sin(px * 0.11 + seed * 7.3)
                               * Math.sin(py * 0.07 + seed * 3.1);
          }
          /* 境界ガード: 最外 2px は変位を 0 へ漸減。backdrop 読取りは要素境界で
             クリップされるため、境界ピクセルが外（透明）をサンプルすると
             チャネル分離 × screen 合成で色が湧く（マゼンタ縁アーティファクト） */
          if (-s < 2) mag *= -s / 2;
          if (mag > 0.002) {
            var nx = roundedSDF(px + e, py, hw, hh, mr) - roundedSDF(px - e, py, hw, hh, mr);
            var ny = roundedSDF(px, py + e, hw, hh, mr) - roundedSDF(px, py - e, hw, hh, mr);
            var len = Math.hypot(nx, ny) || 1;
            dx = (nx / len) * mag;
            dy = (ny / len) * mag;
          }
        }
        var i = (y * mw + x) * 4;
        d[i] = Math.round(128 + dx * 127);
        d[i + 1] = Math.round(128 + dy * 127);
        d[i + 2] = 128;
        d[i + 3] = 255;
      }
    }
    ctx.putImageData(img, 0, 0);
    var uri = c.toDataURL('image/png');
    mapCache.set(key, uri);
    return uri;
  }

  var SVGNS = 'http://www.w3.org/2000/svg';
  var XLINK = 'http://www.w3.org/1999/xlink';
  function prim(name, attrs, parent) {
    var el = document.createElementNS(SVGNS, name);
    for (var k in attrs) el.setAttribute(k, attrs[k]);
    parent.appendChild(el);
    return el;
  }

  function ensureDefs() {
    if (defs) return;
    var svg = document.createElementNS(SVGNS, 'svg');
    svg.setAttribute('width', '0');
    svg.setAttribute('height', '0');
    svg.setAttribute('aria-hidden', 'true');
    svg.style.position = 'absolute';
    defs = document.createElementNS(SVGNS, 'defs');
    svg.appendChild(defs);
    document.body.appendChild(svg);
  }

  /* filter 本体。同一 geometry × variant はフィルタごと共有する */
  function getFilterId(w, h, r, variantName, seed) {
    var V = variants[variantName];
    var falloff = Math.min(w, h) * V.falloffRatio;
    var fkey = w + 'x' + h + 'r' + Math.round(r) + 'v' + variantName + 's' + seed;
    var cached = filterCache.get(fkey);
    if (cached) return cached;

    var minDim = Math.min(w, h);
    var scale = Math.min(V.scaleMax, Math.max(V.scaleMin, minDim * V.scaleRatio));
    var ca = V.ca;
    var uri = makeMapURI(w, h, r, falloff, seed);
    var id = 'lg-lens-' + (idc++);

    var f = prim('filter', {
      id: id, x: '0', y: '0', width: '100%', height: '100%',
      'color-interpolation-filters': 'sRGB'
    }, defs);

    var img = prim('feImage', {
      x: '0', y: '0', width: w, height: h,
      preserveAspectRatio: 'none', result: 'map'
    }, f);
    img.setAttribute('href', uri);
    img.setAttributeNS(XLINK, 'xlink:href', uri);

    /* 分散: 変位比 R 0.86 / G 1.0 / B 1.22。実変位差は ±ca px に clamp
       （色収差はエッジ数 px の上限 — 公理1） */
    var chans = [
      ['dR', Math.max(scale - ca, scale * tok.caR),
        '1 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0'],
      ['dG', scale, '0 0 0 0 0  0 1 0 0 0  0 0 0 0 0  0 0 0 1 0'],
      ['dB', Math.min(scale + ca, scale * tok.caB),
        '0 0 0 0 0  0 0 0 0 0  0 0 1 0 0  0 0 0 1 0']
    ];

    chans.forEach(function (cn) {
      prim('feDisplacementMap', {
        'in': 'SourceGraphic', in2: 'map', scale: cn[1].toFixed(2),
        xChannelSelector: 'R', yChannelSelector: 'G', result: cn[0]
      }, f);
      prim('feColorMatrix', {
        'in': cn[0], type: 'matrix', values: cn[2], result: 'c' + cn[0]
      }, f);
    });
    prim('feBlend', { 'in': 'cdR', in2: 'cdG', mode: 'screen', result: 'rg' }, f);
    prim('feBlend', { 'in': 'rg', in2: 'cdB', mode: 'screen', result: 'rgb' }, f);
    /* 彩度リフトはチェーン内でも適用 — 値は tokens の CSS 変数から（単一ソース） */
    prim('feColorMatrix', { 'in': 'rgb', type: 'saturate', values: String(V.saturate) }, f);

    filterCache.set(fkey, id);
    return id;
  }

  function applyLens(el) {
    if (mode !== 'lens') return;
    ensureTokens();
    var rect = el.getBoundingClientRect();
    var w = Math.round(rect.width), h = Math.round(rect.height);
    if (w < 8 || h < 8) return; /* hidden — 表示時に refresh(el) で再適用 */
    ensureDefs();
    var cs = getComputedStyle(el);
    var r = Math.min(parseFloat(cs.borderTopLeftRadius) || 0, Math.min(w, h) / 2);
    var variantName = el.dataset.lgVariant === 'clear' ? 'clear' : 'regular';
    var V = variants[variantName];
    var seed = el._lgSeed !== undefined ? el._lgSeed : (el._lgSeed = (seedCounter++ + obsSeedOffset) % 4);
    var id = getFilterId(w, h, r, variantName, seed);
    var post = '';
    if (V.chainBlur > 0) post += ' blur(' + V.chainBlur + 'px)';
    if (variantName === 'regular') post += ' brightness(var(--lg-bcomp))';
    el.style.backdropFilter = 'url(#' + id + ')' + post;
    el.style.webkitBackdropFilter = el.style.backdropFilter;
  }

  /* ---------- 応答する光学（R12）----------
     押すとレンズが潰れ、屈折・分散が物理的に弱まる。共有フィルタを
     初回押下時に要素専有へ複製し、変位スケール3枚をバネで駆動する。 */
  function ownFilter(el) {
    if (el._lgFx !== undefined) return el._lgFx;
    var m = (el.style.backdropFilter || '').match(/url\(["']?#(lg-lens-[\w-]+)/);
    if (!m) { el._lgFx = null; return null; }
    var orig = document.getElementById(m[1]);
    if (!orig) { el._lgFx = null; return null; }
    var clone = orig.cloneNode(true);
    var id = m[1] + '-fx-' + (idc++);
    clone.setAttribute('id', id);
    defs.appendChild(clone);
    el.style.backdropFilter = el.style.backdropFilter.replace('#' + m[1], '#' + id);
    el.style.webkitBackdropFilter = el.style.backdropFilter;
    var maps = clone.querySelectorAll('feDisplacementMap');
    var base = [];
    for (var i = 0; i < maps.length; i++) base.push(parseFloat(maps[i].getAttribute('scale')));
    el._lgFx = { maps: maps, base: base };
    return el._lgFx;
  }
  function makeOptics(el) {
    if (mode !== 'lens') return null;
    ensureTokens();
    var s = new Spring(1, tok.k * 0.9, tok.zeta * 0.85); /* ややアンダーダンプ = 揺り戻しで屈折が一度ゆらぐ */
    s.onUpdate = function (f) {
      var fx = el._lgFx;
      if (!fx) return;
      for (var i = 0; i < fx.maps.length; i++) {
        fx.maps[i].setAttribute('scale', (fx.base[i] * f).toFixed(2));
      }
    };
    return {
      to: function (f) { if (ownFilter(el)) s.set(f); }
    };
  }

  function rebuildAll() {
    readTokens(); /* テーマ切替（data-lg-theme）後の値変更を拾う */
    if (mode !== 'lens') return;
    if (defs) defs.textContent = '';
    idc = 0;
    mapCache.clear();
    filterCache.clear();
    document.querySelectorAll('.lg-glass').forEach(applyLens);
  }

  /* ============================================================
     animation core — 共有 rAF。Spring(復帰) + press tween(1:1)。
     入力追従の粘性遅延はこの物質に存在しない（公理5）。
     ============================================================ */
  var anims = new Set();
  var rafOn = false, lastT = 0;
  function tick(t) {
    var dt = Math.min(1 / 30, (t - lastT) / 1000 || 1 / 60);
    lastT = t;
    anims.forEach(function (a) { if (a.step(dt, t)) anims.delete(a); });
    if (anims.size) requestAnimationFrame(tick);
    else rafOn = false;
  }
  function startRaf() {
    if (rafOn) return;
    rafOn = true;
    lastT = performance.now();
    requestAnimationFrame(tick);
  }

  function Spring(value, k, zeta) {
    this.x = value; this.v = 0; this.target = value;
    this.k = k; this.c = 2 * Math.sqrt(k) * zeta;
    this.onUpdate = null;
  }
  Spring.prototype.set = function (t) {
    this.target = t;
    if (reduceMotion) { /* snap */
      this.x = t; this.v = 0;
      if (this.onUpdate) this.onUpdate(t);
      return;
    }
    anims.add(this);
    startRaf();
  };
  Spring.prototype.step = function (dt) {
    var a = -this.k * (this.x - this.target) - this.c * this.v;
    this.v += a * dt;
    this.x += this.v * dt;
    var settled = Math.abs(this.x - this.target) < 0.0004 && Math.abs(this.v) < 0.004;
    if (settled) { this.x = this.target; this.v = 0; }
    if (this.onUpdate) this.onUpdate(this.x);
    return settled;
  };

  /* ---------- gel v2: Squash & Stretch + Follow-through（R14） ----------
     press = 1:1 の即応で「縦に潰れ横に伸びる」（体積保存の squash）
     release / hover = 低減衰バネ（wobble-zeta）でぷるんと揺れて到達する。
     カーソル追従の遅延は存在しない（公理5: 変形にだけ慣性がある） */
  function gel(el, opts) {
    ensureTokens();
    opts = opts || {};
    var squashY = opts.press != null ? opts.press : cssNum('--lg-motion-gel-squash-y', 0.9);
    /* 体積保存: opts.press（部品の1ノブ）からも横伸びを自動導出 */
    var stretchX = opts.press != null
      ? 1 + (1 - opts.press) * 0.7
      : cssNum('--lg-motion-gel-stretch-x', 1.06);
    var hoverS = cssNum('--lg-motion-gel-hover-scale', 1.03);
    var wobble = cssNum('--lg-motion-gel-wobble-zeta', 0.42);
    var k = opts.k || tok.k;

    var sx = new Spring(1, k, wobble);
    var sy = new Spring(1, k, wobble);
    function paint() {
      el.style.transform = 'scale(' + sx.x.toFixed(4) + ', ' + sy.x.toFixed(4) + ')';
    }
    sx.onUpdate = paint;
    sy.onUpdate = paint;

    var st = { hover: false, press: false };
    var pressAnim = null;
    var vit = attachVitals(el);

    function targets() {
      if (st.press) return [stretchX, squashY];
      if (st.hover) return [hoverS, hoverS];
      return [1, 1];
    }
    function settle() { /* バネで（揺れながら）目標へ */
      var t = targets();
      sx.set(t[0]);
      sy.set(t[1]);
    }
    function doPress() { /* 押下だけは 1:1 の即応（バネを使わない） */
      anims.delete(sx); anims.delete(sy);
      if (pressAnim) anims.delete(pressAnim);
      var tx = stretchX, ty = squashY;
      if (reduceMotion) {
        sx.x = sx.target = tx; sy.x = sy.target = ty;
        sx.v = sy.v = 0; paint();
        return;
      }
      var fx = sx.x, fy = sy.x, t0 = performance.now(), ms = tok.pressMs;
      pressAnim = {
        step: function () {
          var p = Math.min(1, (performance.now() - t0) / ms);
          var e = 1 - Math.pow(1 - p, 3);
          sx.x = fx + (tx - fx) * e; sx.v = 0;
          sy.x = fy + (ty - fy) * e; sy.v = 0;
          paint();
          return p >= 1;
        }
      };
      anims.add(pressAnim);
      startRaf();
    }

    el.addEventListener('pointerenter', function (e) {
      if (e.pointerType === 'touch') return; /* touch に hover は無い（離した後の残留を防ぐ） */
      st.hover = true; if (!st.press) settle();
    });
    el.addEventListener('pointerleave', function () { st.hover = false; st.press = false; settle(); });
    /* 祖先のスクロールでは pointerleave/enter が発火せず、:hover の再計算も
       次の mousemove まで走らないことがある（Chrome）。実ヒットテストで判定し、
       流れ出た要素の hover を解除し、流れ込んできた要素へ hover を移す */
    document.addEventListener('scroll', function () {
      var over = lgPointerOver(el);
      if (st.hover && !over) { st.hover = false; st.press = false; settle(); }
      else if (!st.hover && over && !st.press) { st.hover = true; settle(); }
    }, true);
    el.addEventListener('pointerdown', function (e) {
      if (el.setPointerCapture) { try { el.setPointerCapture(e.pointerId); } catch (_) {} }
      st.press = true;
      doPress();
      vit.press(true);
    });
    function release() {
      st.press = false;
      if (pressAnim) { anims.delete(pressAnim); pressAnim = null; }
      settle(); /* 低減衰 → ぷるんと揺れて戻る（follow-through） */
      vit.press(false);
    }
    el.addEventListener('pointerup', release);
    el.addEventListener('pointercancel', release);
    el.addEventListener('lostpointercapture', release);
    el.addEventListener('keydown', function (e) {
      if ((e.key === ' ' || e.key === 'Enter') && !e.repeat) { st.press = true; doPress(); vit.press(true); }
    });
    el.addEventListener('keyup', function (e) {
      if (e.key === ' ' || e.key === 'Enter') release();
    });
    return { sx: sx, sy: sy };
  }

  /* ---------- virtual light: 角度はポインタ 1:1 直結。強度は CSS が遷移 ---------- */
  function light(el) {
    el.addEventListener('pointermove', function (e) {
      var r = el.getBoundingClientRect();
      var dx = e.clientX - (r.left + r.width / 2);
      var dy = e.clientY - (r.top + r.height / 2);
      var deg = Math.atan2(dy, dx) * 180 / Math.PI + 90; /* css conic: 0 = up */
      el.style.setProperty('--lg-la', deg.toFixed(1) + 'deg');
    });
  }


  /* ---------- 生命徴 vital signs（R13）----------
     瞳孔反射: hover でレンズがわずかに締まる（操作への応答・公理内）
     注視の呼吸: focus-visible の間だけリム強度がゆっくり往復
     （公理4の唯一の例外。apple-quiet では depth=0 で消灯） */
  function attachVitals(el) {
    if (el._lgVitals) return el._lgVitals;
    var optics = makeOptics(el); /* baseline では null */
    var st = { hover: false, press: false };
    function apply() {
      if (!optics) return;
      var pressF = cssNum('--lg-motion-gel-optics-press', 0.3);
      var hoverF = cssNum('--lg-motion-gel-optics-hover', 0.92);
      optics.to(st.press ? pressF : st.hover ? hoverF : 1);
    }
    el.addEventListener('pointerenter', function (e) {
      if (e.pointerType === 'touch') return; /* touch に hover は無い */
      st.hover = true; apply();
    });
    el.addEventListener('pointerleave', function () { st.hover = false; st.press = false; apply(); });
    document.addEventListener('scroll', function () { /* スクロールで hover が置き去り/未着になるのを防ぐ */
      var over = lgPointerOver(el);
      if (st.hover && !over) { st.hover = false; st.press = false; apply(); }
      else if (!st.hover && over && !st.press) { st.hover = true; apply(); }
    }, true);

    var breath = null;
    function startBreath() {
      if (breath || reduceMotion) return;
      var depth = cssNum('--lg-light-breath-depth', 0);
      if (depth <= 0) return;
      var period = cssNum('--lg-light-breath-period', 3600);
      var base = cssNum('--lg-light-hover-intensity', 0.8);
      var t0 = performance.now();
      breath = { step: function (dt, t) {
        var phase = ((t - t0) % period) / period;
        var li = base * (1 - depth * (0.5 + 0.5 * Math.sin(phase * 2 * Math.PI)));
        el.style.setProperty('--lg-li', li.toFixed(3));
        return false; /* focusout まで生きる */
      } };
      anims.add(breath);
      startRaf();
    }
    function stopBreath() {
      if (breath) { anims.delete(breath); breath = null; }
      el.style.removeProperty('--lg-li');
    }
    el.addEventListener('focusin', function () {
      try {
        if (el.matches(':focus-visible') || el.querySelector(':focus-visible')) startBreath();
      } catch (_) {}
    });
    el.addEventListener('focusout', stopBreath);

    var api = { press: function (on) { st.press = !!on; apply(); } };
    el._lgVitals = api;
    return api;
  }

  /* ---------- nav: sprung pill（横 / 縦 lg-nav--vertical / lg-segmented 共用） ---------- */
  function nav(navEl) {
    ensureTokens();
    var pill = navEl.querySelector('.lg-nav-pill');
    var tabs = Array.prototype.slice.call(navEl.querySelectorAll('.lg-tab'));
    if (!tabs.length) return;
    if (!pill) { /* ピルは自動生成（マークアップ簡略化） */
      pill = document.createElement('span');
      pill.className = 'lg-nav-pill';
      pill.setAttribute('aria-hidden', 'true');
      navEl.insertBefore(pill, navEl.firstChild);
    }
    var vertical = navEl.classList.contains('lg-nav--vertical');
    var sx = new Spring(0, tok.k * 0.75, Math.min(0.75, tok.zeta + 0.05));
    var sw = new Spring(0, tok.k * 0.75, Math.min(0.8, tok.zeta + 0.1));
    sx.onUpdate = function (x) {
      pill.style.transform = (vertical ? 'translateY(' : 'translateX(') + x.toFixed(2) + 'px)';
    };
    sw.onUpdate = function (w) {
      pill.style[vertical ? 'height' : 'width'] = w.toFixed(2) + 'px';
    };
    function move(tab, instant) {
      var x = vertical ? tab.offsetTop : tab.offsetLeft;
      var w = vertical ? tab.offsetHeight : tab.offsetWidth;
      if (instant || reduceMotion) {
        sx.x = sx.target = x; sw.x = sw.target = w;
        sx.onUpdate(x); sw.onUpdate(w);
      } else { sx.set(x); sw.set(w); }
    }
    function syncPanels() {
      tabs.forEach(function (t) {
        var pid = t.getAttribute('aria-controls');
        if (!pid) return;
        var p = document.getElementById(pid);
        if (p) {
          p.setAttribute('role', 'tabpanel');
          p.hidden = t.getAttribute('aria-selected') !== 'true';
        }
      });
    }
    tabs.forEach(function (tab) {
      tab.setAttribute('role', 'tab');
      tab.addEventListener('click', function () {
        tabs.forEach(function (t) {
          t.setAttribute('aria-selected', String(t === tab));
        });
        syncPanels();
        move(tab, false);
      });
      gel(tab, { press: cssNum('--lg-nav-tab-press-scale', 0.94), k: tok.k * 1.15 });
    });
    var active = navEl.querySelector('.lg-tab[aria-selected="true"]') || tabs[0];
    active.setAttribute('aria-selected', 'true');
    syncPanels();
    move(active, true);
    navEl._lgRelayout = function () { move(navEl.querySelector('.lg-tab[aria-selected="true"]') || tabs[0], true); };
  }

  /* ---------- modal: gel 開閉 + scrim ---------- */
  function modal(backdropEl) {
    ensureTokens();
    var pane = backdropEl.querySelector('.lg-modal');
    var s = new Spring(tok.modalEnter, tok.k * 0.85, tok.zeta);
    s.onUpdate = function (x) { if (pane) pane.style.transform = 'scale(' + x.toFixed(4) + ')'; };
    var lastFocus = null;
    function open() {
      lastFocus = document.activeElement;
      backdropEl.classList.add('is-open');
      backdropEl.setAttribute('aria-hidden', 'false');
      if (pane) {
        applyLens(pane); /* 非表示中に測れなかった場合の保険 */
        s.x = tok.modalEnter; s.v = 0;
        s.set(1);
        pane.focus && pane.focus();
      }
    }
    function close() {
      backdropEl.classList.remove('is-open');
      backdropEl.setAttribute('aria-hidden', 'true');
      s.set(tok.modalEnter);
      if (lastFocus && lastFocus.focus) lastFocus.focus();
    }
    backdropEl.addEventListener('click', function (e) {
      if (e.target === backdropEl) close();
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && backdropEl.classList.contains('is-open')) close();
    });
    return { open: open, close: close };
  }

  /* ============================================================
     phase 3 — SaaS parts: menu / select / command / toast /
     tooltip / switch / slider / chip。
     すべて既存物理を共有: 入場はバネ、退場はフェード、追従は 1:1。
     ============================================================ */

  function springScale(el, from, k, zeta) {
    var s = new Spring(from, k || tok.k * 0.85, zeta || tok.zeta);
    s.onUpdate = function (x) { el.style.transform = 'scale(' + x.toFixed(4) + ')'; };
    return s;
  }

  /* ---------- menu: トリガーからバネでモーフ入場、フェード退場 ---------- */
  var openMenus = [];
  function menu(anchorEl) {
    ensureTokens();
    var trigger = anchorEl.querySelector('button:not(.lg-menu-item), .lg-select-trigger');
    var panel = anchorEl.querySelector('.lg-menu');
    if (!trigger || !panel) return null;
    var enterScale = cssNum('--lg-menu-enter-scale', 0.65);
    var s = springScale(panel, enterScale, tok.k * 0.9);
    var isPopover = panel.classList.contains('lg-menu--popover');
    trigger.setAttribute('aria-haspopup', 'true');
    trigger.setAttribute('aria-expanded', 'false');
    panel.setAttribute('role', panel.getAttribute('role') || (isPopover ? 'dialog' : 'menu'));
    var isOpen = false;
    function items() {
      return Array.prototype.slice.call(panel.querySelectorAll('.lg-menu-item'))
        .filter(function (i) { return !i.hidden && !i.disabled; });
    }
    items().forEach(function (i) {
      if (!i.getAttribute('role')) i.setAttribute('role', 'menuitem');
    });
    function open() {
      if (isOpen) return;
      isOpen = true;
      panel.classList.add('is-open');
      trigger.setAttribute('aria-expanded', 'true');
      applyLens(panel);
      s.x = enterScale; s.v = 0; s.set(1);
      openMenus.push(api);
      var first = isPopover
        ? panel.querySelector('input, select, textarea, button, [tabindex]')
        : items()[0];
      if (first) first.focus();
    }
    function close(refocus) {
      if (!isOpen) return;
      isOpen = false;
      panel.classList.remove('is-open');
      trigger.setAttribute('aria-expanded', 'false');
      s.set(enterScale);
      var ix = openMenus.indexOf(api);
      if (ix > -1) openMenus.splice(ix, 1);
      if (refocus) trigger.focus();
    }
    trigger.addEventListener('click', function () { if (isOpen) close(true); else open(); });
    panel.addEventListener('click', function (e) {
      if (!isPopover && e.target.closest('.lg-menu-item')) close(true);
    });
    panel.addEventListener('keydown', function (e) {
      var list = items();
      var i = list.indexOf(document.activeElement);
      if (e.key === 'ArrowDown') { e.preventDefault(); (list[i + 1] || list[0]).focus(); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); (list[i - 1] || list[list.length - 1]).focus(); }
      else if (e.key === 'Escape') { e.preventDefault(); e.stopPropagation(); close(true); }
    });
    var api = { open: open, close: close, el: anchorEl, panel: panel, trigger: trigger };
    anchorEl._lgMenu = api;
    return api;
  }
  document.addEventListener('pointerdown', function (e) {
    openMenus.slice().forEach(function (m) {
      if (!m.el.contains(e.target)) m.close(false);
    });
  });
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && openMenus.length) {
      openMenus[openMenus.length - 1].close(true);
    }
  });

  /* ---------- select: menu を土台にした単一選択 ---------- */
  function select(selectEl) {
    var api = menu(selectEl);
    if (!api) return null;
    api.panel.setAttribute('role', 'listbox');
    var label = selectEl.querySelector('.lg-select-label');
    var opts = Array.prototype.slice.call(api.panel.querySelectorAll('.lg-menu-item'));
    opts.forEach(function (o) {
      o.setAttribute('role', 'option');
      if (!o.hasAttribute('aria-selected')) o.setAttribute('aria-selected', 'false');
      o.addEventListener('click', function () {
        opts.forEach(function (x) { x.setAttribute('aria-selected', String(x === o)); });
        if (label) label.textContent = o.dataset.lgLabel || o.textContent.trim();
        selectEl.dispatchEvent(new CustomEvent('lg-change', {
          detail: { value: o.dataset.lgValue != null ? o.dataset.lgValue : o.textContent.trim() }
        }));
      });
    });
    return api;
  }

  /* ---------- command: ⌘K パレット ---------- */
  function command(backdropEl) {
    ensureTokens();
    var pane = backdropEl.querySelector('.lg-command');
    var input = backdropEl.querySelector('.lg-command-input');
    var empty = backdropEl.querySelector('.lg-command-empty');
    if (!pane || !input) return null;
    var s = springScale(pane, tok.modalEnter, tok.k * 0.85);
    var lastFocus = null;
    function allItems() {
      return Array.prototype.slice.call(backdropEl.querySelectorAll('.lg-command-item'));
    }
    function visItems() { return allItems().filter(function (i) { return !i.hidden; }); }
    function setActive(item) {
      allItems().forEach(function (i) { i.classList.toggle('is-active', i === item); });
      if (item && item.scrollIntoView) item.scrollIntoView({ block: 'nearest' });
    }
    function filter() {
      var q = (input.value || '').trim().toLowerCase();
      allItems().forEach(function (i) {
        i.hidden = q !== '' && i.textContent.toLowerCase().indexOf(q) === -1;
      });
      var vis = visItems();
      if (empty) empty.hidden = vis.length > 0;
      setActive(vis[0] || null);
    }
    function open() {
      lastFocus = document.activeElement;
      backdropEl.classList.add('is-open');
      backdropEl.setAttribute('aria-hidden', 'false');
      applyLens(pane);
      input.value = '';
      filter();
      s.x = tok.modalEnter; s.v = 0; s.set(1);
      input.focus();
    }
    function close() {
      backdropEl.classList.remove('is-open');
      backdropEl.setAttribute('aria-hidden', 'true');
      s.set(tok.modalEnter);
      if (lastFocus && lastFocus.focus) lastFocus.focus();
    }
    input.addEventListener('input', filter);
    backdropEl.addEventListener('click', function (e) {
      if (e.target.closest('.lg-command-item')) close();
    });
    backdropEl.addEventListener('keydown', function (e) {
      var vis = visItems();
      var active = backdropEl.querySelector('.lg-command-item.is-active');
      var i = vis.indexOf(active);
      if (e.key === 'ArrowDown') { e.preventDefault(); setActive(vis[Math.min(i + 1, vis.length - 1)] || vis[0]); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); setActive(vis[Math.max(i - 1, 0)] || vis[0]); }
      else if (e.key === 'Enter') { if (active) { active.click(); close(); } }
      else if (e.key === 'Escape') { e.stopPropagation(); close(); }
    });
    backdropEl.addEventListener('click', function (e) { if (e.target === backdropEl) close(); });
    document.addEventListener('keydown', function (e) {
      if ((e.metaKey || e.ctrlKey) && (e.key === 'k' || e.key === 'K')) {
        e.preventDefault();
        if (backdropEl.classList.contains('is-open')) close(); else open();
      }
    });
    return { open: open, close: close, filter: filter };
  }

  /* ---------- toast: 右下スタック。入場バネ・退場フェード・hover で滞留 ---------- */
  var toastStack = null;
  function toast(msg, opts) {
    ensureTokens();
    opts = opts || {};
    if (!toastStack) {
      toastStack = document.createElement('div');
      toastStack.className = 'lg-toast-stack';
      toastStack.setAttribute('role', 'status');
      toastStack.setAttribute('aria-live', 'polite');
      document.body.appendChild(toastStack);
    }
    var t = document.createElement('div');
    t.className = 'lg-toast lg-glass' + (opts.positive ? ' is-positive' : '');
    if (opts.surface) t.setAttribute('data-lg-surface', opts.surface);
    var span = document.createElement('span');
    span.textContent = msg;
    t.appendChild(span);
    var timer = null;
    var remain = cssNum('--lg-ref-duration-toast', 4200);
    var t0 = 0;
    function dismiss() {
      clearTimeout(timer); timer = null;
      t.classList.add('is-leaving');
      setTimeout(function () { if (t.parentNode) t.parentNode.removeChild(t); }, tok.fadeMs + 40);
    }
    function schedule(ms) { t0 = Date.now(); timer = setTimeout(dismiss, ms); }
    if (opts.action) {
      var b = document.createElement('button');
      b.className = 'lg-toast-action';
      b.textContent = opts.action;
      gel(b, { press: cssNum('--lg-nav-tab-press-scale', 0.94) });
      b.addEventListener('click', function () {
        if (opts.onAction) opts.onAction();
        dismiss();
      });
      t.appendChild(b);
    }
    while (toastStack.children.length >= 4) toastStack.removeChild(toastStack.firstChild);
    toastStack.appendChild(t);
    applyLens(t);
    light(t);
    var s = new Spring(1, tok.k * 0.9, tok.zeta);
    s.onUpdate = function (x) {
      t.style.transform = 'translateY(' + (x * 14).toFixed(2) + 'px) scale(' + (1 - 0.04 * x).toFixed(4) + ')';
    };
    s.set(0);
    t.addEventListener('pointerenter', function () {
      if (timer) { clearTimeout(timer); remain = Math.max(1200, remain - (Date.now() - t0)); timer = null; }
    });
    t.addEventListener('pointerleave', function () { if (!timer && !t.classList.contains('is-leaving')) schedule(remain); });
    if (opts.sticky !== true) schedule(remain);
    return { dismiss: dismiss, el: t };
  }

  /* ---------- tooltip: 遅延表示・位置固定（ポインタ非追従） ---------- */
  var tipEl = null, tipTimer = null, tipTarget = null;
  function ensureTip() {
    if (tipEl) return tipEl;
    tipEl = document.createElement('div');
    tipEl.className = 'lg-tooltip';
    tipEl.id = 'lg-tooltip';
    tipEl.setAttribute('role', 'tooltip');
    document.body.appendChild(tipEl);
    return tipEl;
  }
  function showTip(target) {
    var el = ensureTip();
    el.textContent = target.getAttribute('data-lg-tooltip') || '';
    el.classList.remove('is-open');
    el.style.left = '0px'; el.style.top = '0px';
    var r = target.getBoundingClientRect();
    var tw = el.offsetWidth, th = el.offsetHeight;
    var x = Math.min(Math.max(8, r.left + r.width / 2 - tw / 2), innerWidth - tw - 8);
    var y = r.top - th - 8;
    if (y < 8) y = r.bottom + 8;
    el.style.left = x.toFixed(0) + 'px';
    el.style.top = y.toFixed(0) + 'px';
    el.classList.add('is-open');
    target.setAttribute('aria-describedby', 'lg-tooltip');
    tipTarget = target;
  }
  function hideTip() {
    clearTimeout(tipTimer); tipTimer = null;
    if (tipEl) tipEl.classList.remove('is-open');
    if (tipTarget) { tipTarget.removeAttribute('aria-describedby'); tipTarget = null; }
  }
  function tooltip(target) {
    function arm() {
      clearTimeout(tipTimer);
      tipTimer = setTimeout(function () { showTip(target); },
        cssNum('--lg-ref-duration-tooltip-delay', 450));
    }
    target.addEventListener('pointerenter', arm);
    target.addEventListener('focus', arm);
    target.addEventListener('pointerleave', hideTip);
    target.addEventListener('blur', hideTip);
    target.addEventListener('pointerdown', hideTip);
  }
  window.addEventListener('scroll', hideTip, true);

  /* ---------- switch: ノブは gel バネで滑走。操作中ガラス化は CSS 側 ---------- */
  function switchCtl(switchEl) {
    ensureTokens();
    var input = switchEl.querySelector('input');
    var track = switchEl.querySelector('.lg-switch-track');
    var knob = switchEl.querySelector('.lg-switch-knob');
    if (!input || !track || !knob) return;
    var s = new Spring(0, tok.k * 1.1, tok.zeta);
    s.onUpdate = function (x) { knob.style.transform = 'translateX(' + x.toFixed(2) + 'px)'; };
    function travel() { return track.offsetWidth - track.offsetHeight; }
    function sync(instant) {
      var x = input.checked ? travel() : 0;
      if (instant || reduceMotion) { s.x = s.target = x; s.v = 0; s.onUpdate(x); }
      else s.set(x);
    }
    input.addEventListener('change', function () { sync(false); });
    sync(true);
    switchEl._lgRelayout = function () { sync(true); };
  }

  /* ---------- slider: 値は 1:1（追従遅延なし）。塗り位置を CSS 変数へ ---------- */
  function slider(el) {
    function sync() {
      var min = parseFloat(el.min) || 0;
      var max = isNaN(parseFloat(el.max)) ? 100 : parseFloat(el.max);
      var p = ((parseFloat(el.value) - min) / (max - min || 1)) * 100;
      el.style.setProperty('--lg-slider-val', p.toFixed(2) + '%');
    }
    el.addEventListener('input', sync);
    sync();
  }

  /* ---------- chip: aria-pressed トグル ---------- */
  function chip(el) {
    el.addEventListener('click', function () {
      el.setAttribute('aria-pressed', String(el.getAttribute('aria-pressed') !== 'true'));
    });
  }

  /* ---------- phase 4: textarea autosize / banner dismiss / progress ---------- */
  function autosize(ta) {
    function sync() {
      ta.style.height = 'auto';
      ta.style.height = ta.scrollHeight + 'px';
    }
    ta.addEventListener('input', sync);
    sync();
  }

  function banner(el) {
    var close = el.querySelector('.lg-banner-close');
    if (!close) return;
    close.addEventListener('click', function () {
      el.classList.add('is-leaving');
      setTimeout(function () { if (el.parentNode) el.parentNode.removeChild(el); }, tok.fadeMs + 40);
    });
  }

  function progress(el, value) {
    if (value != null) el.dataset.lgValue = value;
    var v = parseFloat(el.dataset.lgValue);
    if (!isNaN(v)) el.style.setProperty('--lg-progress-val', Math.max(0, Math.min(100, v)) + '%');
    el.setAttribute('role', 'progressbar');
    if (!el.classList.contains('is-indeterminate')) {
      el.setAttribute('aria-valuemin', '0');
      el.setAttribute('aria-valuemax', '100');
      el.setAttribute('aria-valuenow', String(isNaN(v) ? 0 : v));
    }
  }

  /* ============================================================
     phase 5 — drawer / context menu / combobox / datepicker /
     number / dropzone / mobile shell
     ============================================================ */

  /* ---------- drawer: 右からの一時面。translateX バネ入場 ---------- */
  function drawer(backdropEl) {
    ensureTokens();
    var pane = backdropEl.querySelector('.lg-drawer');
    var off = cssNum('--lg-drawer-enter-offset', 28);
    var s = new Spring(off, tok.k * 0.85, tok.zeta);
    s.onUpdate = function (x) { if (pane) pane.style.transform = 'translateX(' + x.toFixed(2) + 'px)'; };
    var lastFocus = null;
    function open() {
      lastFocus = document.activeElement;
      backdropEl.classList.add('is-open');
      backdropEl.setAttribute('aria-hidden', 'false');
      if (pane) {
        applyLens(pane);
        s.x = off; s.v = 0; s.set(0);
        var first = pane.querySelector('input, select, textarea, button, [tabindex]');
        if (first) first.focus();
      }
    }
    function close() {
      backdropEl.classList.remove('is-open');
      backdropEl.setAttribute('aria-hidden', 'true');
      s.set(off);
      if (lastFocus && lastFocus.focus) lastFocus.focus();
    }
    backdropEl.addEventListener('click', function (e) { if (e.target === backdropEl) close(); });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && backdropEl.classList.contains('is-open')) close();
    });
    backdropEl._lgDrawer = { open: open, close: close };
    return backdropEl._lgDrawer;
  }

  /* ---------- context menu: カーソル位置に開く（右クリック結合） ---------- */
  function contextMenu(target, panel) {
    ensureTokens();
    var enterScale = cssNum('--lg-menu-enter-scale', 0.65);
    var s = springScale(panel, enterScale, tok.k * 0.9);
    var isOpen = false;
    function close() {
      if (!isOpen) return;
      isOpen = false;
      panel.classList.remove('is-open');
      s.set(enterScale);
    }
    function openAt(x, y) {
      applyLens(panel);
      var w = panel.offsetWidth || 208, h = panel.offsetHeight || 40;
      panel.style.left = Math.max(8, Math.min(x, innerWidth - w - 8)) + 'px';
      panel.style.top = Math.max(8, Math.min(y, innerHeight - h - 8)) + 'px';
      panel.classList.add('is-open');
      isOpen = true;
      s.x = enterScale; s.v = 0; s.set(1);
    }
    target.addEventListener('contextmenu', function (e) {
      e.preventDefault();
      openAt(e.clientX, e.clientY);
    });
    panel.addEventListener('click', function (e) {
      if (e.target.closest('.lg-menu-item')) close();
    });
    document.addEventListener('pointerdown', function (e) {
      if (isOpen && !panel.contains(e.target)) close();
    });
    document.addEventListener('keydown', function (e) { if (e.key === 'Escape') close(); });
    return { openAt: openAt, close: close };
  }

  /* ---------- combobox: 入力でフィルタする select ---------- */
  function combobox(el) {
    ensureTokens();
    var input = el.querySelector('.lg-field-input');
    var panel = el.querySelector('.lg-menu');
    if (!input || !panel) return null;
    panel.setAttribute('role', 'listbox');
    var enterScale = cssNum('--lg-menu-enter-scale', 0.65);
    var s = springScale(panel, enterScale, tok.k * 0.9);
    var isOpen = false;
    function opts() { return Array.prototype.slice.call(panel.querySelectorAll('.lg-menu-item')); }
    function filter() {
      var q = input.value.trim().toLowerCase();
      opts().forEach(function (o) {
        o.hidden = q !== '' && o.textContent.toLowerCase().indexOf(q) === -1;
      });
    }
    function open() {
      if (isOpen) return;
      isOpen = true;
      applyLens(panel);
      panel.classList.add('is-open');
      s.x = enterScale; s.v = 0; s.set(1);
    }
    function close() {
      if (!isOpen) return;
      isOpen = false;
      panel.classList.remove('is-open');
      s.set(enterScale);
    }
    function pick(o) {
      input.value = o.dataset.lgLabel || o.textContent.trim();
      el.dispatchEvent(new CustomEvent('lg-change', {
        detail: { value: o.dataset.lgValue != null ? o.dataset.lgValue : input.value }
      }));
      close();
    }
    input.addEventListener('focus', function () { filter(); open(); });
    input.addEventListener('input', function () { filter(); open(); });
    input.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') close();
      else if (e.key === 'Enter' && isOpen) {
        var first = opts().filter(function (o) { return !o.hidden; })[0];
        if (first) { e.preventDefault(); pick(first); }
      }
    });
    panel.addEventListener('click', function (e) {
      var o = e.target.closest('.lg-menu-item');
      if (o) pick(o);
    });
    document.addEventListener('pointerdown', function (e) {
      if (isOpen && !el.contains(e.target)) close();
    });
    return { open: open, close: close };
  }

  /* ---------- number input: ステッパーボタン。min/max/step を尊重 ---------- */
  function numberField(fieldEl) {
    var input = fieldEl.querySelector('.lg-field-input');
    if (!input) return;
    fieldEl.querySelectorAll('.lg-step').forEach(function (b) {
      b.addEventListener('click', function () {
        var step = (parseFloat(input.step) || 1) * (parseFloat(b.dataset.step) || 1);
        var v = (parseFloat(input.value) || 0) + step;
        if (input.min !== '') v = Math.max(v, parseFloat(input.min));
        if (input.max !== '') v = Math.min(v, parseFloat(input.max));
        var dec = (String(input.step).split('.')[1] || '').length;
        input.value = v.toFixed(dec);
        input.dispatchEvent(new Event('input', { bubbles: true }));
        input.dispatchEvent(new Event('change', { bubbles: true }));
      });
    });
  }

  /* ---------- datepicker: input[data-lg-datepicker] に popover カレンダー ---------- */
  function datepicker(input) {
    ensureTokens();
    var panel = document.createElement('div');
    panel.className = 'lg-glass lg-menu lg-menu--context lg-datepicker';
    panel.setAttribute('role', 'dialog');
    panel.setAttribute('aria-label', '日付を選択');
    document.body.appendChild(panel);
    var enterScale = cssNum('--lg-menu-enter-scale', 0.65);
    var s = springScale(panel, enterScale, tok.k * 0.9);
    var view = new Date();
    var isOpen = false;
    function pad2(n) { return (n < 10 ? '0' : '') + n; }
    function fmt(d) { return d.getFullYear() + '-' + pad2(d.getMonth() + 1) + '-' + pad2(d.getDate()); }
    function render() {
      var y = view.getFullYear(), m = view.getMonth();
      var sel = input.value, today = fmt(new Date());
      var start = (new Date(y, m, 1).getDay() + 6) % 7; /* 月曜始まり */
      var ic = function (n, fb) {
        return window.LGIcons ? window.LGIcons.svg(n) : fb;
      };
      var html = '<div class="lg-datepicker-head">' +
        '<button class="lg-step" data-nav="-1" aria-label="前の月">' + ic('chevron-left', '‹') + '</button>' +
        '<span>' + y + '年' + (m + 1) + '月</span>' +
        '<button class="lg-step" data-nav="1" aria-label="次の月">' + ic('chevron-right', '›') + '</button></div>' +
        '<div class="lg-datepicker-grid">';
      ['月', '火', '水', '木', '金', '土', '日'].forEach(function (d) {
        html += '<span class="dow">' + d + '</span>';
      });
      for (var i = 0; i < 42; i++) {
        var d = new Date(y, m, i - start + 1);
        var ds = fmt(d);
        html += '<button class="day' + (d.getMonth() !== m ? ' is-out' : '') +
          (ds === today ? ' is-today' : '') + '" data-date="' + ds + '"' +
          ' aria-selected="' + (ds === sel) + '">' + d.getDate() + '</button>';
      }
      panel.innerHTML = html + '</div>';
      panel.querySelectorAll('.lg-step').forEach(function (b) {
        gel(b, { press: cssNum('--lg-nav-tab-press-scale', 0.94) });
      });
    }
    function position() {
      var anchor = input.closest('.lg-field') || input;
      var r = anchor.getBoundingClientRect();
      panel.style.left = '0px'; panel.style.top = '0px';
      var w = panel.offsetWidth, h = panel.offsetHeight;
      var x = Math.max(8, Math.min(r.left, innerWidth - w - 8));
      var y = r.bottom + 6;
      if (y + h > innerHeight - 8) y = Math.max(8, r.top - h - 6);
      panel.style.left = x.toFixed(0) + 'px';
      panel.style.top = y.toFixed(0) + 'px';
    }
    function open() {
      if (isOpen) return;
      isOpen = true;
      if (input.value) {
        var p = input.value.split('-');
        if (p.length === 3) view = new Date(+p[0], +p[1] - 1, 1);
      }
      render();
      position();
      applyLens(panel);
      panel.classList.add('is-open');
      s.x = enterScale; s.v = 0; s.set(1);
    }
    function close() {
      if (!isOpen) return;
      isOpen = false;
      panel.classList.remove('is-open');
      s.set(enterScale);
    }
    input.addEventListener('focus', open);
    input.addEventListener('click', open);
    input.addEventListener('keydown', function (e) { if (e.key === 'Escape') close(); });
    panel.addEventListener('click', function (e) {
      var nav = e.target.closest('[data-nav]');
      if (nav) {
        view.setMonth(view.getMonth() + parseInt(nav.dataset.nav, 10));
        render();
        return;
      }
      var day = e.target.closest('.day');
      if (day) {
        input.value = day.dataset.date;
        input.dispatchEvent(new Event('input', { bubbles: true }));
        input.dispatchEvent(new CustomEvent('lg-change', { detail: { value: day.dataset.date } }));
        close();
      }
    });
    document.addEventListener('pointerdown', function (e) {
      if (isOpen && !panel.contains(e.target) && e.target !== input) close();
    });
    return { open: open, close: close };
  }

  /* ---------- dropzone: drag over の間だけガラス化。lg-files イベント発火 ---------- */
  function dropzone(zone) {
    var input = zone.querySelector('input[type="file"]');
    var files = zone.querySelector('.files');
    if (!zone.hasAttribute('tabindex')) zone.setAttribute('tabindex', '0');
    zone.setAttribute('role', 'button');
    function setFiles(list) {
      if (files) {
        files.textContent = Array.prototype.map.call(list, function (f) { return f.name; }).join(' / ');
      }
      zone.dispatchEvent(new CustomEvent('lg-files', { detail: { files: list } }));
    }
    zone.addEventListener('click', function () { if (input) input.click(); });
    zone.addEventListener('keydown', function (e) {
      if ((e.key === 'Enter' || e.key === ' ') && input) { e.preventDefault(); input.click(); }
    });
    if (input) input.addEventListener('change', function () { setFiles(input.files); });
    ['dragenter', 'dragover'].forEach(function (ev) {
      zone.addEventListener(ev, function (e) { e.preventDefault(); zone.classList.add('is-over'); });
    });
    ['dragleave', 'drop'].forEach(function (ev) {
      zone.addEventListener(ev, function (e) { e.preventDefault(); zone.classList.remove('is-over'); });
    });
    zone.addEventListener('drop', function (e) {
      if (e.dataTransfer && e.dataTransfer.files.length) setFiles(e.dataTransfer.files);
    });
  }

  /* ---------- mobile shell: サイドバーのオフキャンバス開閉 ---------- */
  function shellNav(shell) {
    shell.querySelectorAll('.lg-shell-menu-btn, [data-lg-shell-toggle]').forEach(function (b) {
      b.addEventListener('click', function () { shell.classList.toggle('is-nav-open'); });
    });
    /* mobile: 明示的な閉じるボタンをサイドバーへ注入（scrim/Esc に加えて） */
    var sb = shell.querySelector('.lg-sidebar');
    if (sb && !sb.querySelector('.lg-shell-close')) {
      var c = document.createElement('button');
      c.className = 'lg-shell-close';
      c.setAttribute('aria-label', 'メニューを閉じる');
      c.innerHTML = window.LGIcons ? LGIcons.svg('x') : '\u2715';
      c.addEventListener('click', function () { shell.classList.remove('is-nav-open'); });
      sb.appendChild(c);
    }
    shell.addEventListener('click', function (e) {
      if (e.target === shell && shell.classList.contains('is-nav-open')) {
        shell.classList.remove('is-nav-open');
      }
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') shell.classList.remove('is-nav-open');
    });
  }

  /* ---------- offscreen pause ---------- */
  var io = ('IntersectionObserver' in window)
    ? new IntersectionObserver(function (entries) {
        entries.forEach(function (en) {
          en.target.classList.toggle('lg-offscreen', !en.isIntersecting);
        });
      }, { rootMargin: '96px' })
    : null;

  /* ---------- init ---------- */
  var resizeT = null;
  function onResize() {
    clearTimeout(resizeT);
    resizeT = setTimeout(function () {
      rebuildAll();
      document.querySelectorAll('.lg-nav, .lg-segmented, .lg-switch').forEach(function (n) {
        if (n._lgRelayout) n._lgRelayout();
      });
    }, 200);
  }

  function init() {
    readTokens();
    initObserver(); /* 観測者効果（R16）: レンズ生成より先に確定 */
    initPhysique(); /* 体質（R17）: gel/lens が読む前に trait を適用 */
    initSignals();  /* 環境信号（R18）: 太陽・傾き・バッテリー・懐き */
    document.querySelectorAll('.lg-glass').forEach(function (el) {
      applyLens(el);
      light(el);
      attachVitals(el);
      if (io) io.observe(el);
    });
    document.querySelectorAll('[data-lg-animate]').forEach(function (el) {
      if (io) io.observe(el);
    });
    document.querySelectorAll('[data-lg-gel]').forEach(function (el) {
      var press = parseFloat(el.dataset.lgGel);
      gel(el, isNaN(press) ? {} : { press: press });
    });
    /* 弾性は素材共通の物性（R14 補遺）: 操作できる塗り部品にも gel を標準搭載。
       光学（屈折・リム・呼吸）はガラスのみ = 二層の希少性は不変 */
    document.querySelectorAll(
      '.lg-chip, .lg-pagination-item, .lg-icon-button, .lg-select-trigger, ' +
      '.lg-step, .lg-shell-menu-btn'
    ).forEach(function (el) {
      if (el.dataset.lgGel === undefined) {
        gel(el, { press: cssNum('--lg-nav-tab-press-scale', 0.94) });
      }
    });
    document.querySelectorAll('.lg-nav').forEach(nav);
    document.querySelectorAll('.lg-segmented').forEach(nav);
    document.querySelectorAll('.lg-select:not(.lg-combobox)').forEach(select);
    document.querySelectorAll('.lg-combobox').forEach(combobox);
    document.querySelectorAll('.lg-backdrop--drawer').forEach(function (b) {
      if (!b._lgDrawer) drawer(b);
    });
    document.querySelectorAll('[data-lg-context]').forEach(function (t) {
      var p = document.querySelector(t.dataset.lgContext);
      if (p) contextMenu(t, p);
    });
    document.querySelectorAll('.lg-field--number').forEach(numberField);
    document.querySelectorAll('input[data-lg-datepicker]').forEach(datepicker);
    document.querySelectorAll('.lg-dropzone').forEach(dropzone);
    document.querySelectorAll('.lg-shell').forEach(shellNav);
    document.querySelectorAll('.lg-menu-anchor').forEach(function (el) {
      if (!el._lgMenu) menu(el);
    });
    document.querySelectorAll('.lg-backdrop--command').forEach(command);
    document.querySelectorAll('[data-lg-tooltip]').forEach(tooltip);
    document.querySelectorAll('.lg-switch').forEach(switchCtl);
    document.querySelectorAll('.lg-slider').forEach(slider);
    document.querySelectorAll('.lg-chip[aria-pressed]').forEach(chip);
    document.querySelectorAll('textarea.lg-field-input[data-lg-autosize]').forEach(autosize);
    document.querySelectorAll('.lg-banner').forEach(banner);
    document.querySelectorAll('.lg-progress').forEach(function (el) { progress(el); });
    window.addEventListener('resize', onResize);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
  window.addEventListener('load', function () { rebuildAll(); });

  /* ---------- public API ---------- */
  window.LiquidGlass = {
    mode: mode,
    observer: function () { return observerInfo; },
    physique: function () { return physiqueInfo; },
    signals: function () { return signalsInfo; },
    enableTilt: function () { /* iOS: ユーザー操作の中から呼ぶこと */
      if (!tiltAttach) return Promise.resolve('off');
      if (typeof DeviceOrientationEvent !== 'undefined' &&
          typeof DeviceOrientationEvent.requestPermission === 'function') {
        return DeviceOrientationEvent.requestPermission().then(function (s) {
          if (s === 'granted') tiltAttach();
          return s;
        });
      }
      tiltAttach();
      return Promise.resolve('granted');
    },
    reducedMotion: reduceMotion,
    reducedTransparency: reduceTransp,
    refresh: rebuildAll,
    lens: applyLens,
    gel: gel,
    light: light,
    nav: nav,
    modal: modal,
    menu: menu,
    select: select,
    command: command,
    toast: toast,
    tooltip: tooltip,
    switch: switchCtl,
    slider: slider,
    progress: progress,
    drawer: drawer,
    contextMenu: contextMenu,
    combobox: combobox,
    datepicker: datepicker,
    dropzone: dropzone,
    Spring: Spring
  };
})();
