#!/usr/bin/env node
/* build-dist.mjs — src/manifest.json の順に分割ソースを連結して dist を生成。依存ゼロ。
   構造はアトミックデザイン: src/{foundations,atoms,molecules,organisms,templates}/<部品>/
   連結順（cascade / 実行順）は manifest が唯一の正。usage: node tools/build-dist.mjs */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(readFileSync(join(root, 'src/manifest.json'), 'utf8'));

function concat(files, outFile) {
  const banner = `/* generated by tools/build-dist.mjs — DO NOT EDIT. 編集は src/ のアトミック分割ソースへ */\n`;
  const body = banner + files.map((f) => readFileSync(join(root, f), 'utf8')).join('\n');
  writeFileSync(join(root, outFile), body);
  console.log(`${outFile}: ${files.length} parts, ${(body.length / 1024).toFixed(1)}KB`);
}
concat(manifest.css, 'css/liquid-glass.css');
concat(manifest.js, 'js/liquid-glass.js');
