#!/usr/bin/env node
/* build-icons.mjs — assets/icons/*.svg → js/lg-icons.js（インライン sprite 注入スクリプト）
   出典: Lucide (https://lucide.dev) ISC License。依存ゼロ。
   usage: node tools/build-icons.mjs */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, resolve, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(root, 'assets/icons');
const symbols = [];
const names = [];

for (const f of readdirSync(srcDir).filter((f) => f.endsWith('.svg')).sort()) {
  const name = basename(f, '.svg');
  const svg = readFileSync(join(srcDir, f), 'utf8');
  const m = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!m) { console.error('skip (no svg):', f); continue; }
  const inner = m[1].replace(/\s+/g, ' ').trim();
  symbols.push(`<symbol id="lg-i-${name}" viewBox="0 0 24 24">${inner}</symbol>`);
  names.push(name);
}

const js = `/* generated by tools/build-icons.mjs — DO NOT EDIT
   icons: Lucide v1.x (https://lucide.dev) — ISC License
   使い方: <i data-lg-icon="${names[0]}"></i> → .lg-icon の svg に置換される */
(function () {
  'use strict';
  var SPRITE = '${symbols.join('')}';
  var NAMES = ${JSON.stringify(names)};
  function ensureSprite() {
    if (document.getElementById('lg-icon-sprite')) return;
    var host = document.createElement('div');
    host.innerHTML = '<svg id="lg-icon-sprite" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">' + SPRITE + '</svg>';
    document.body.insertBefore(host.firstChild, document.body.firstChild);
  }
  function svg(name, cls) {
    return '<svg class="lg-icon' + (cls ? ' ' + cls : '') + '" aria-hidden="true" focusable="false">' +
      '<use href="#lg-i-' + name + '"></use></svg>';
  }
  function scan(rootEl) {
    ensureSprite();
    (rootEl || document).querySelectorAll('[data-lg-icon]').forEach(function (el) {
      var name = el.getAttribute('data-lg-icon');
      if (NAMES.indexOf(name) === -1) return;
      var tpl = document.createElement('template');
      tpl.innerHTML = svg(name, el.getAttribute('data-lg-icon-class') || '');
      var node = tpl.content.firstChild;
      el.replaceWith(node);
    });
  }
  function init() { ensureSprite(); scan(document); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
  window.LGIcons = { svg: svg, scan: scan, names: NAMES.slice() };
})();
`;
writeFileSync(join(root, 'js/lg-icons.js'), js);
console.log('lg-icons.js: ' + names.length + ' icons — ' + names.join(', '));
