#!/usr/bin/env node
/* build-pages.mjs — ページの参照合成（案A）。依存ゼロ。
   src/pages/<page>/index.html を起点に、
     <!-- @include <root相対パス> {"key":"value"} -->
   を再帰解決して showcase/<page>.html を生成する。
   パーシャル側は {{key=既定値}} で差し替え点を宣言できる
   （params 未指定・キー未指定なら既定値のまま = 正規マークアップとして単体でも読める）。
   usage: node tools/build-pages.mjs */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const INC = /<!--\s*@include\s+(\S+)(?:\s+(\{[\s\S]*?\}))?\s*-->/g;
const VAR = /\{\{([a-zA-Z0-9_-]+)(?:=((?:[^{}]|\{[^{}]*\})*?))?\}\}/g;

function render(path, params, stack) {
  if (stack.includes(path)) throw new Error('循環 include: ' + stack.concat(path).join(' → '));
  let s = readFileSync(join(root, path), 'utf8');
  /* {{key=default}} の解決 */
  s = s.replace(VAR, (_, key, def) =>
    params && key in params ? String(params[key]) : (def !== undefined ? def : `{{${key}}}`));
  /* 子 include の解決 */
  s = s.replace(INC, (_, incPath, json) => {
    const p = json ? JSON.parse(json) : null;
    return render(incPath, p, stack.concat(path)).trim();
  });
  return s;
}

const pagesDir = join(root, 'src/pages');
if (!existsSync(pagesDir)) {
  console.log('src/pages/ がありません');
  process.exit(0);
}
for (const page of readdirSync(pagesDir, { withFileTypes: true })) {
  if (!page.isDirectory()) continue;
  const entry = `src/pages/${page.name}/index.html`;
  if (!existsSync(join(root, entry))) continue;
  const out = render(entry, null, []);
  const banner = `<!-- generated by tools/build-pages.mjs — DO NOT EDIT. 編集は ${`src/pages/${page.name}/`} と各部品の src/ へ -->\n`;
  writeFileSync(join(root, `showcase/${page.name}.html`), banner + out);
  console.log(`showcase/${page.name}.html ← ${entry}（参照合成）`);
}
