#!/usr/bin/env node
/* build-tokens.mjs — DTCG tokens → CSS custom properties. 依存ゼロ。
   source: src/tokens/{ref,sys,comp}/*.tokens.json（役割別の分割ソース。編集はここ）
   core  : マージ → tokens/liquid-glass.tokens.json（生成物）→ css/tokens.css (:root)
   theme : tokens/themes/{name}.tokens.json → css/themes/{name}.css ([data-lg-theme])
   usage : node tools/build-tokens.mjs */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, resolve, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

/* ---------- src/tokens/ を深マージ（葉の衝突は警告） ---------- */
function deepMerge(dst, src, path, from) {
  for (const k of Object.keys(src)) {
    const v = src[k];
    if (v && typeof v === 'object' && !('$value' in v) && dst[k] && typeof dst[k] === 'object') {
      deepMerge(dst[k], v, path + '/' + k, from);
    } else {
      if (k in dst && k !== '$description') {
        console.warn(`! 衝突: ${path}/${k}（${from} が上書き）`);
      }
      dst[k] = v;
    }
  }
  return dst;
}

function loadMerged() {
  const srcRoot = resolve(here, '../src');
  const doc = {};
  /* 1) foundations/tokens/{ref,sys} */
  for (const layer of ['ref', 'sys']) {
    const dir = join(srcRoot, 'foundations/tokens', layer);
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir).filter((f) => f.endsWith('.tokens.json')).sort()) {
      deepMerge(doc, JSON.parse(readFileSync(join(dir, f), 'utf8')), '', layer + '/' + f);
    }
  }
  /* 2) comp = 各部品フォルダの *.tokens.json（atoms/molecules/organisms/templates） */
  const compFiles = [];
  (function walk(dir) {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith('.tokens.json')) compFiles.push(p);
    }
  })(srcRoot);
  for (const p of compFiles.filter((p) => !p.includes('foundations')).sort()) {
    deepMerge(doc, JSON.parse(readFileSync(p, 'utf8')), '', p.replace(srcRoot, 'src'));
  }
  return doc;
}


const SYS = new Set(['material', 'light', 'adaptive', 'motion', 'observer', 'physique', 'signals']);
const COMP = new Set(['button', 'card', 'nav', 'modal', 'field']);

const aliasToVar = (s) =>
  s.replace(/\{([^}]+)\}/g, (_, p) => `var(--${p.split('.').join('-')})`);

function cssValue(tok) {
  const v = tok.$value;
  if (typeof v === 'string') return aliasToVar(v);
  if (tok.$type === 'cubicBezier' && Array.isArray(v))
    return `cubic-bezier(${v.join(', ')})`;
  if (tok.$type === 'shadow') {
    const list = Array.isArray(v) ? v : [v];
    return list
      .map((s) =>
        `${s.inset ? 'inset ' : ''}${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${aliasToVar(s.color)}`)
      .join(', ');
  }
  return String(v);
}

function buildFile(srcPath, outPath, selector, label) {
  const doc = typeof srcPath === 'string'
    ? JSON.parse(readFileSync(srcPath, 'utf8'))
    : srcPath;
  const lines = [];
  const counts = { ref: 0, sys: 0, comp: 0 };

  (function walk(node, path) {
    if (node && typeof node === 'object' && '$value' in node) {
      lines.push(`  --${path.join('-')}: ${cssValue(node)};`);
      const layer = path[1] === 'ref' ? 'ref' : SYS.has(path[1]) ? 'sys' : 'comp';
      counts[layer]++;
      return;
    }
    if (node && typeof node === 'object') {
      for (const k of Object.keys(node)) {
        if (!k.startsWith('$')) walk(node[k], path.concat(k));
      }
    }
  })(doc, []);

  const css = `/* generated by tools/build-tokens.mjs — DO NOT EDIT
   source: ${typeof srcPath === 'string' ? basename(srcPath) : 'src/tokens/ (merged)'}
   ref ${counts.ref} / sys ${counts.sys} / comp ${counts.comp} tokens */
${selector} {
${lines.join('\n')}
}
`;
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, css);
  console.log(`${label}: ref ${counts.ref} / sys ${counts.sys} / comp ${counts.comp} (total ${counts.ref + counts.sys + counts.comp}) → ${outPath.replace(/^.*04_production\//, '')}`);
}

/* core — src/tokens をマージし、統合 JSON（生成物）と CSS を出力 */
const merged = loadMerged();
writeFileSync(
  resolve(here, '../tokens/liquid-glass.tokens.json'),
  JSON.stringify(merged, null, 2) + '\n'
);
buildFile(merged, resolve(here, '../css/tokens.css'), ':root', 'core');

/* themes（変数上書きのみ。セレクタや構造は含めない） */
const themesDir = resolve(here, '../tokens/themes');
if (existsSync(themesDir)) {
  for (const f of readdirSync(themesDir)) {
    if (!f.endsWith('.tokens.json')) continue;
    const name = f.replace(/\.tokens\.json$/, '');
    buildFile(
      join(themesDir, f),
      resolve(here, `../css/themes/${name}.css`),
      `[data-lg-theme="${name}"]`,
      `theme ${name}`
    );
  }
}
